### ISSUE TITLE
syscall: 'watch <some file>' errno: 'ENOSPC'

### ISSUE THREAD

**Issue by bmsdave** [GoogleChromeLabs/ndb#110]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.20
* Platform / OS version: Ubuntu 18.04.1 LTS
uname -rvpo: 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 GNU/Linux
* Node.js version: v8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. goto folder witch 8193 files or more
It is important to exceed the number ```cat /proc/sys/fs/inotify/max_user_watches```
2. run ```ndb```

**What is the expected result?**
```
code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /***.jsonp',
  filename: '/***.jsonp' }
{ Error: watch /***.jsonp ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/bmsdave/.nvm/versions/node/v8.11.3/lib/node_modules/ndb/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/bmsdave/.nvm/versions/node/v8.11.3/lib/node_modules/ndb/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/bmsdave/.nvm/versions/node/v8.11.3/lib/node_modules/ndb/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/bmsdave/.nvm/versions/node/v8.11.3/lib/node_modules/ndb/node_modules/chokidar/lib/nodefs-handler.js:259:21)
    at FSWatcher.<anonymous> (/home/bmsdave/.nvm/versions/node/v8.11.3/lib/node_modules/ndb/node_modules/chokidar/lib/nodefs-handler.js:480:21)
    at FSReqWrap.oncomplete (fs.js:153:5)

```

**What happens instead?**
If possible, please allow the exclusion of files from watching.
Or warn the user that not all files will be watched.

**Related**
https://stackoverflow.com/questions/22475849/node-js-error-enospc/32600959
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by ak239** [comment]
Latest `ndb@1.0.40` should behave much better with big folders, it works better with node 10.
You can go to settings -> workspace -> and edit folder exclude pattern to exclude some folders.
For watching we rely on `chokidar` and for now, unfortunately we can not do anything better so I will close this and I hope that exclude pattern + improved ndb will resolve this issue for you.
