### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by ztzven** [GoogleChromeLabs/ndb#131]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.24
* Platform / OS version: Windows
* Node.js version: 10.8.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. run ndb index.js
2. close ndb (via Control - C in terminal)
3. produces error

**What is the expected result?**

nsb to exit cleanly

**What happens instead?**

```
$ fs.js:113
    throw err;
    ^

Error: EPERM: operation not permitted, unlink 'C:\Users\<>\AppData\Local\Temp\ndb-z76sce\BrowserMetrics\BrowserMetrics-5B8E07F9-3AAC.pma'
    at Object.unlinkSync (fs.js:916:3)
    at fixWinEPERMSync (C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:211:13)
    at rimrafSync (C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:311:28)
    at C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:334:7)
    at fixWinEPERMSync (C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:209:5)
    at rimrafSync (C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:311:28)
    at C:\Users\<>\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:342:5
```

**Comment by istiti** [comment]
Not sure if it is related issue. I'm trying debug my app but ndb take too long to responde something so I 
 don't know if ndb is blocked somewhere but I want stop/cancel my running "ndb node ..." command using CTRL+C, it result in : 
```
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\eee\AppData\Local\Temp\ndb-ZZVls5\Crashpad'
    at Object.rmdirSync (fs.js:677:3)
    at rmkidsSync (C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:334:7)
    at Function.rimrafSync [as sync] (C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\node_modules\rimraf\rimraf.js:304:9)
    at process.on._ (C:\Users\eee\AppData\Roaming\npm\node_modules\ndb\lib\launcher.js:141:18)
```

My versions:
ndb : 1.0.26 
os: windows 10
node :  10.12.0
npm : 6.4.1

@ak239 let me know if I need create new issue.

**Comment by ak239** [comment]
`ndb@1.0.40` copies much less files around so this issue should be resolved. Feel free to commend if you still can reproduce it.
