### ISSUE TITLE
Node process hangs after NDB terminates

### ISSUE THREAD

**Issue by radum** [GoogleChromeLabs/ndb#136]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.24
* Platform / OS version: macOS High Sierra 10.13.6
* Node.js version: v10.10.0

**What steps will reproduce the problem?**

Any node file with any code.

1. Run `ndb test.js`
2. Debug and then close the debugger, checking the console the node process exits and you get control of your terminal
3. Checking the process monitor there is a node process still running, and while checking its info looks like the one running for our test file.

**What is the expected result?**

If NDB closes and the node process exits the process should be terminated.

**What happens instead?**

The node process keeps running causing wasted memory usage.

Here is a dump of the process info:

```
cwd
/Users/rmicu/test
txt
/Users/rmicu/.nvm/versions/node/v10.10.0/bin/node
txt
/Users/rmicu/.nvm/versions/node/v10.10.0/lib/node_modules/ndb/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
txt
/usr/lib/dyld
txt
/private/var/db/dyld/dyld_shared_cache_x86_64h
0
/dev/ttys001
1
/dev/ttys001
2
/dev/ttys001
4
count=0, state=0xa
5
->0xb6d401481007dd3b
6
->0xb6d401481007ce3b
7
->0xb6d401481007e1bb
8
->0xb6d401481007eb7b
9
->0xb6d401481007d8bb
10
->0xb6d401481007d7fb
11
count=0, state=0
12
->0xb6d401481007da3b
13
->0xb6d401481007e4bb
14
->0xb6d401481007e93b
15
->0xb6d401481007f2fb
16
count=0, state=0xa
17
->0xb6d401481007dc7b
18
->0xb6d401481007ccbb
19
->0xb6d401480555a4fb
20
->0xb6d401480555c3bb
21
/dev/null
22
/dev/ttys001
23
/dev/ttys001
24
count=0, state=0x9
25
/private/var/folders/lm/y6ps3jj958d1knmt0f1l5s40flrtv4/T
26
/private/var/folders/lm/y6ps3jj958d1knmt0f1l5s40flrtv4/T/ndb-bRPJPe
27
/private/var/folders/lm/y6ps3jj958d1knmt0f1l5s40flrtv4
28
/private/var/folders/lm
29
/private/var/folders
30
/private/var
31
/private
32
count=0, state=0x9
33
->0xb6d4014823d68003
36
localhost:54360->localhost:54357
```

And if I terminate the process manually this logs to the console:

```
❯ events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:628:16)
    at Promise.resolve.then.result (/Users/rmicu/.nvm/versions/node/v10.10.0/lib/node_modules/ndb/services/service_base.js:23:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:632:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by ak239** [comment]
Please check latest ndb version (1.0.25), it includes fix for this. Thanks for your report!
