### ISSUE TITLE
unable to open file explorer with node v8.10

### ISSUE THREAD

**Issue by ashwinsoni** [GoogleChromeLabs/ndb#241]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.43
* Platform / OS version: macOS Mojave 10.14.3
* Node.js version: 8.10

**What steps will reproduce the problem?**
Using the below package version:
  - esm => 3.0.84
  - ndb => 1.0.26

- setup ndb with node version 8.10 and run below command
> ndb -r esm index.js

_Please include code that reproduces the issue._
[skip]

**What is the expected result?**
- Source>Filesystem should have file explorer open and allow the app to debug

**What happens instead?**
- ndb has opened with no source
- no error in terminal and the app is not starting
- after terminating the app getting the below error,
```(node:9172) UnhandledPromiseRejectionWarning: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at Rpc.routeMessage_ (/Users/ashwinsoni/test-ndb/node_modules/carlo/rpc/rpc.js:393:10)
    at Rpc.sendCommand_ (/Users/ashwinsoni/test-ndb/node_modules/carlo/rpc/rpc.js:333:10)
    at Handle.callMethod_ (/Users/ashwinsoni/test-ndb/node_modules/carlo/rpc/rpc.js:79:38)
    at WebSocket.ws.once (/Users/ashwinsoni/test-ndb/node_modules/ndb/services/ndd_service.js:95:24)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/Users/ashwinsoni/test-ndb/node_modules/ws/lib/websocket.js:180:10)
    at Socket.socketOnClose (/Users/ashwinsoni/test-ndb/node_modules/ws/lib/websocket.js:802:15)

**Comment by felixdrp** [comment]
Please, have a look to [239#](https://github.com/GoogleChromeLabs/ndb/issues/239#issuecomment-467815984). Does it work for you?

**Comment by ashwinsoni** [comment]
Thanks @felixdrp for the reference.
Still the error persist.

**Comment by ak239** [comment]
Please check out `ndb@1.0.47` it contains more reliable implementation of file system.

**Comment by ak239** [comment]
Feel free to comment this issue or file another one if you still can reproduce it with latest ndb release.

**Comment by ashwinsoni** [comment]
Thanks, @ak239 for the update. Yes `ndb@1.047` works amazing.
