### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by felixdrp** [GoogleChromeLabs/ndb#248]
I updated to ndb (1.0.44)... the error persisted. The only difference is that now I have an error message:
ndb
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

If I close the Chrome browser it works...

_Originally posted by @felixdrp in https://github.com/GoogleChromeLabs/ndb/issues/239#issuecomment-473857079_

**Comment by ak239** [comment]
There is even more generic tracking issue for all similar problems: https://github.com/GoogleChromeLabs/ndb/issues/204
