### ISSUE TITLE
Folder exclude option or respect .gitignore

### ISSUE THREAD

**Issue by duzun** [GoogleChromeLabs/ndb#253]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.44
* Platform / OS version: Linux 5.1.1-2-MANJARO x86_64
* Node.js version: v11.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. In dev, I have mongodb with db folder in `./data/db` (and some other data stuff in `./data/` folder).
2. In `./files/` I have some hundreds of thousands of files, trying to be as close to production as possible.

**What is the expected result?**

When mongodb is running, `./data/db` folder is not accessible, and `ndb` throws an error:

```log
Error: EACCES: permission denied, scandir '{root}/data/db/admin'
    at Object.readdirSync (fs.js:806:3)
    at FileSystemHandler.filePaths (~/.npm-global/lib/node_modules/ndb/services/file_system.js:62:26)
```

And because of `./files/` folder, `ndb` is very slow (see #229).

**What happens instead?**

`ndb` should ignore both `./data/` and `./files/` folders, because there is no code in those folders, and they both are ignored in `.gitignore`.
Or at least it would be nice to have an option to specify which folders to be ignored.

**Comment by ak239** [comment]
You can go to Settings > Workspace and edit `Folder exclude pattern` to add any folders that should be ignored.
![image](https://user-images.githubusercontent.com/426418/59821020-4c2f2b00-92e0-11e9-95ba-320c7deed596.png)

**Comment by duzun** [comment]
Thanks @ak239
I didn’t know about workspaces...
Still, would be nice if ndb respects .gitignore, that would be one thing less to worry about.
