### ISSUE TITLE
ndb performance profiler crash

### ISSUE THREAD

**Issue by romainmnr** [GoogleChromeLabs/ndb#302]
The ndb debugger keep crashing while stoping the performace profile record.

**What steps will reproduce the problem?**
- launche ndb `ndb npm start`
- start recording performance
- stop recording
- CRASH

### Crash report

```
/usr/local/lib/node_modules/ndb/services/ndd_service.js:21
  throw error;
  ^

Error: TypeError: Cannot read property 'originStackTrace' of null
TypeError: Cannot read property 'originStackTrace' of null
    at Function._script (https://domain/sources/sources_module.js:13:76808)
    at Sources.ScriptOriginPlugin.rightToolbarItems (https://domain/sources/sources_module.js:13:76463)
    at Sources.UISourceCodeFrame.syncToolbarItems (https://domain/sources/sources_module.js:1:52187)
    at Sources.SourcesView._updateScriptViewToolbarItems (https://domain/sources/sources_module.js:13:39654)
    at Sources.SourcesView._editorClosed (https://domain/sources/sources_module.js:13:41002)
    at Sources.TabbedEditorContainer.dispatchEventToListeners (https://domain/ndb.js:1:91157)
    at Sources.TabbedEditorContainer._tabClosed (https://domain/sources/sources_module.js:13:9996)
    at UI.TabbedPane.dispatchEventToListeners (https://domain/ndb.js:1:91157)
    at UI.TabbedPane._innerCloseTab (https://domain/ndb.js:1:971597)
    at UI.TabbedPane.closeTabs (https://domain/ndb.js:1:971046)
    at Rpc.dispatchMessageLocally_ (/usr/local/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:423:16)
    at Rpc.routeMessage_ (/usr/local/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:371:12)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:628:16)
    at Rpc.routeMessage_ (/usr/local/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:379:9)
    at page_.exposeFunction.data (/usr/local/lib/node_modules/ndb/node_modules/carlo/lib/carlo.js:388:71)
    at Page._onBindingCalled (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:548:56)
    at CDPSession.Page.client.on.event (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:136:54)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onMessage (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:200:12)
    at Connection._onMessage (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:112:17)
    at PipeTransport._dispatch (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/PipeTransport.js:65:24)
    at Socket.PipeTransport._eventListeners.helper.addEventListener.buffer (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/PipeTransport.js:30:64)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:632:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Tell us about your environment:**

* ndb version: 1.1.5
* Platform / OS version: macOs Catalina 10.15.2 
* Node.js version: v10.13.0

**Comment by junjie-xyz** [comment]
Same problem occurred to me.

- ndb version: 1.1.5
- Platform / OS version: macOs Catalina 10.15.2
- Node.js version: v10.18.0

**Comment by lantto** [comment]
Same here, as soon as I press "Stop" on the profiler to get the results:

```
/usr/local/lib/node_modules/ndb/services/ndd_service.js:21
  throw error;
  ^

Error: TypeError: Cannot read property 'originStackTrace' of null
TypeError: Cannot read property 'originStackTrace' of null
    at Function._script (https://domain/sources/sources_module.js:13:76808)
    at Sources.ScriptOriginPlugin.rightToolbarItems (https://domain/sources/sources_module.js:13:76463)
    at Sources.UISourceCodeFrame.syncToolbarItems (https://domain/sources/sources_module.js:1:52187)
    at Sources.SourcesView._updateScriptViewToolbarItems (https://domain/sources/sources_module.js:13:39654)
    at Sources.SourcesView._editorClosed (https://domain/sources/sources_module.js:13:41002)
    at Sources.TabbedEditorContainer.dispatchEventToListeners (https://domain/ndb.js:1:91157)
    at Sources.TabbedEditorContainer._tabClosed (https://domain/sources/sources_module.js:13:9996)
    at UI.TabbedPane.dispatchEventToListeners (https://domain/ndb.js:1:91157)
    at UI.TabbedPane._innerCloseTab (https://domain/ndb.js:1:971597)
    at UI.TabbedPane.closeTabs (https://domain/ndb.js:1:971046)
    at Rpc.dispatchMessageLocally_ (/usr/local/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:423:16)
    at Rpc.routeMessage_ (/usr/local/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:371:12)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at Rpc.routeMessage_ (/usr/local/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:379:9)
    at /usr/local/lib/node_modules/ndb/node_modules/carlo/lib/carlo.js:388:71
    at Page._onBindingCalled (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:548:56)
    at CDPSession.<anonymous> (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:136:54)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:200:12)
    at Connection._onMessage (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:112:17)
    at PipeTransport._dispatch (/usr/local/lib/node_modules/ndb/node_modules/puppeteer-core/lib/PipeTransport.js:65:24)
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```

ndb version: 1.1.5
Platform / OS version: macOs Catalina 10.15.2
Node.js version: v12.18.2

**Comment by paulirish** [comment]
I've reproduced this plenty of times. At this point it's a known issue of the project. 

I have successfully managed to capture a profile with the latest NDB but it certainly doesn't work consistently.

@brendankenny notes that a possible workaround may be using `console.profile()` and `console.profileEnd()`

**Comment by remorses** [comment]
I got a different stack trace
```
/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/services/ndd_service.js:21
  throw error;
  ^

Error: Error: not implemented
Error: not implemented
    at Ndb.FileSystem.getMetadata (https://domain/ndb.js:3:175663)
    at Persistence.FileSystemWorkspaceBinding.FileSystem.requestMetadata (https://domain/ndb.js:3:131825)
    at Workspace.UISourceCode.requestMetadata (https://domain/ndb.js:1:648280)
    at n (https://domain/ndb.js:3:141810)
    at https://domain/ndb.js:3:141759
    at Array.map (<anonymous>)
    at Persistence.Automapping._pullMetadatas (https://domain/ndb.js:3:141752)
    at Persistence.Automapping._createBinding (https://domain/ndb.js:3:141234)
    at Persistence.Automapping._computeNetworkStatus (https://domain/ndb.js:3:138667)
    at Persistence.Automapping._onUISourceCodeAdded (https://domain/ndb.js:3:137732)
    at Rpc.dispatchMessageLocally_ (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:423:16)
    at Rpc.routeMessage_ (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:371:12)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:762:20)
    at ChildProcess.target.send (internal/child_process.js:634:19)
    at Rpc.routeMessage_ (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:379:9)
    at page_.exposeFunction.data (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/carlo/lib/carlo.js:388:71)
    at Page._onBindingCalled (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:548:56)
    at CDPSession.Page.client.on.event (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:136:54)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:200:12)
    at Connection._onMessage (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:112:17)
    at PipeTransport._dispatch (/Users/morse/.nvm/versions/node/v10.21.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/PipeTransport.js:59:22)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:766:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)

```

**Comment by shapkarin** [comment]
Does anyone solve that?

**Comment by segevofer** [comment]
same here, using mac with node v12.18.0 and ndb v1.1.5
please help resolve this issue...
