### ISSUE TITLE
Error: read ECONNRESET when starting ndb on ubuntu

### ISSUE THREAD

**Issue by Ravi-Rajpurohit** [GoogleChromeLabs/ndb#312]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.1.5
* Platform / OS version: ubuntu/18.04
* Node.js version: 12.16.3

**What steps will reproduce the problem?**

ndb filename.js 
OR
ndb npm run script

_Please include code that reproduces the issue._

1. ndb filename.js 
2. ndb npm run script

**What is the expected result?**

ndb should start the debugger

**What happens instead?**

ndb throws an error: 

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by hcgaron** [comment]
Same exact error for me.  Same system exactly.  No luck so far in resolving.

**Comment by Ravi-Rajpurohit** [comment]
It works with yarn BTW..

**Comment by nicomt** [comment]
Is because Chrome cannot be run as root by default.
A workaround is to install ndb in a directory that doesn't require elevated permissions.
For example `npm install -g --prefix=$HOME/.npm ndb`
and then add the npm bin folder to the path `export PATH="$HOME/.npm/bin:$PATH"`.

**Comment by ksully1993** [comment]
@nicomt Thank you, this solution is perfect

**Comment by att14** [comment]
That did seem to work for me, however, I needed to uninstall my existing `ndb` and `brew uninstall chromium`.

**Comment by AmritPant** [comment]
> Is because Chrome cannot be run as root by default. A workaround is to install ndb in a directory that doesn't require elevated permissions. For example `npm install -g --prefix=$HOME/.npm ndb` and then add the npm bin folder to the path `export PATH="$HOME/.npm/bin:$PATH"`.

Thanks so much working for me!
