### ISSUE TITLE
Seems to fail in rush/pnpm project

### ISSUE THREAD

**Issue by knownasilya** [GoogleChromeLabs/ndb#315]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.1.5
* Platform / OS version: macos
* Node.js version: 10.13

**What steps will reproduce the problem?**

Clone https://github.com/Strider-CD/strider/tree/chore/rush
and do install `npm install -g @microsoft/rush` (https://rushjs.io/pages/intro/get_started/)
Setup repo: `rush install` which installs with pnpm.

Get this error when running `env DEBUG='strider*' ndb yarn watch-lib` (Same error if using `npx`).

```sh
⋊> ~/m/s/a/strider on chore/rush ◦ env DEBUG='strider*' ndb yarn watch-lib                             10:29:43
yarn run v1.17.3
$ nodemon
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'ndb/preload.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:811:12)
    at preloadModules (internal/bootstrap/node.js:594:7)
    at startup (internal/bootstrap/node.js:275:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**What is the expected result?**
Expect ndb to start the server.

**What happens instead?**
The error shows up and the devtools page stays open but nothing else happens.

**Comment by octogonz** [comment]
I haven't used `ndb` before, but it looks cool! We should figure out why this isn't working.

**Comment by diminutivesloop** [comment]
I got this error too when I tried to debug `yarn dev` in the [mdn/yari](https://github.com/mdn/yari/) project.

**Comment by schemar** [comment]
I get the same for `ndb ./node_modules/.bin/react-scripts start`

**Comment by liuliangsir** [comment]
I get the same for `ndb styleguidist server`

**Comment by jauhman** [comment]
Terima kasih



















SELAMAT BERBAGI.


Jakarta 21 Desember. 2010


James Manalu





Pada tanggal Sen, 17 Mei 2021 pukul 13.51 流浪大法师 ***@***.***>
menulis:
