### ISSUE TITLE
events.js:174       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by sagarora77** [GoogleChromeLabs/ndb#324]
Getting Unhandled 'error' event when using ndb after global installation

### Steps to reproduce
ndb app.js or ndb node app.js

**Tell us about your environment:**

* ndb version: 1.1.5
* Platform / OS version: Ubuntu 18.0
* Node.js version: 10.23.0

**What steps will reproduce the problem?**
ndb app.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Not getting ndb to work with Ubuntu 18.0.

**Comment by tracycollins** [comment]
i'm seeing the same error, but I"m running on macOS big sur

- ndb v1.1.5
- macOS v11.1
- node v14.15.1

**Comment by Amirrkhan** [comment]
same error Ubuntu 20.04

- ndb v 1.1.5
- node v10.19.0

Any solution?
