### ISSUE TITLE
ndb throwing an error when worker process terminates

### ISSUE THREAD

**Issue by CyberPhoenix90** [GoogleChromeLabs/ndb#40]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: reproduced on 1.0.7 and 1.0.8
* Platform / OS version: Ubuntu 16.04
* Node.js version: 10.6

**What steps will reproduce the problem?**

When my worker process what I spawned with fork is closed. ndb throws an error which seems relaed to source maps. My project is in typescript so I do have source maps.

**What is the expected result?**

ndb should not throw an error

**What happens instead?**

ndb throws an error:
(node:14426) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'removeSourceMap' of undefined
    at Bindings.CompilerScriptMapping._sourceMapDetached (https://ndb/ndb_app.js:3:686547)
    at SDK.SourceMapManager.dispatchEventToListeners (https://ndb/ndb_app.js:3:35936)
    at SDK.SourceMapManager.detachSourceMap (https://ndb/ndb_app.js:3:550767)
    at SDK.DebuggerModel.executionContextDestroyed (https://ndb/ndb_app.js:3:410805)
    at SDK.RuntimeModel._executionContextDestroyed (https://ndb/ndb_app.js:3:472262)
    at SDK.RuntimeDispatcher.executionContextDestroyed (https://ndb/ndb_app.js:3:479963)
    at Protocol.InspectorBackend._DispatcherPrototype.dispatch (https://ndb/ndb_app.js:3:129987)
    at SDK.Target._onMessage (https://ndb/ndb_app.js:3:124318)
    at Ndb.NodeProcessManager._onMessage (https://ndb/ndb_app.js:3:647449)
    at Ndb.NodeProcessManager._onNotification (https://ndb/ndb_app.js:3:645088)
    at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/ndb/node_modules/puppeteer/lib/ExecutionContext.js:97:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ak239** [comment]
Thanks for your report!
This one should be fixed in just published 1.0.16.
