### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by wenjiasen** [GoogleChromeLabs/ndb#42]
`npm install -g ndb`

### Steps to reproduce

**Tell us about your environment:**

* ndb version:
* Platform / OS version: 
MacOS 10.13.4
* Node.js version:
v8.2.1
**What steps will reproduce the problem?**
`npm install -g ndb`

**What is the expected result?**
Successful installation

**What happens instead?**

```
silly postinstall ndb@1.0.8
4741 info lifecycle ndb@1.0.8~postinstall: ndb@1.0.8
4742 verbose lifecycle ndb@1.0.8~postinstall: unsafe-perm in lifecycle true
4743 verbose lifecycle ndb@1.0.8~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/ndb/node_modules/.bin:/usr/local/lib/node_modules/.bin:/Users/wenjiasen/bin:/Users/wenjiasen/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/wenjiasen/bin:/Users/wenjiasen/go/bin:/usr/local/Cellar/gradle/4.3.1/libexec/bin:/Users/wenjiasen/Library/Android/sdk/tools:/Users/wenjiasen/Library/Android/sdk/platform-tools:/usr/local/Cellar/gradle/4.3.1/libexec/bin:/Users/wenjiasen/Library/Android/sdk/tools:/Users/wenjiasen/Library/Android/sdk/platform-tools
4744 verbose lifecycle ndb@1.0.8~postinstall: CWD: /usr/local/lib/node_modules/ndb
4745 silly lifecycle ndb@1.0.8~postinstall: Args: [ '-c', 'node install.js' ]
4746 silly lifecycle ndb@1.0.8~postinstall: Returned: code: 1  signal: null
4747 info lifecycle ndb@1.0.8~postinstall: Failed to exec postinstall script
4748 verbose unlock done using /Users/wenjiasen/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
4749 verbose stack Error: ndb@1.0.8 postinstall: `node install.js`
4749 verbose stack Exit status 1
4749 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
4749 verbose stack     at emitTwo (events.js:125:13)
4749 verbose stack     at EventEmitter.emit (events.js:213:7)
4749 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4749 verbose stack     at emitTwo (events.js:125:13)
4749 verbose stack     at ChildProcess.emit (events.js:213:7)
4749 verbose stack     at maybeClose (internal/child_process.js:921:16)
4749 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
4750 verbose pkgid ndb@1.0.8
4751 verbose cwd /Users/wenjiasen/Documents/develop/code/web
4752 verbose Darwin 17.5.0
4753 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ndb"
4754 verbose node v8.2.1
4755 verbose npm  v5.6.0
4756 error code ELIFECYCLE
4757 error errno 1
4758 error ndb@1.0.8 postinstall: `node install.js`
4758 error Exit status 1
4759 error Failed at the ndb@1.0.8 postinstall script.
4759 error This is probably not a problem with npm. There is likely additional logging output above.
4760 verbose exit [ 1, true ]

```

**Comment by ak239** [comment]
What way to install node by itself did you use? Have you used official installer or downloaded tar or used nvm?

**Comment by wenjiasen** [comment]
`brew intall node`
@ak239

**Comment by wenjiasen** [comment]
I am sure the node is installed normally. Maybe I should talk about upgrading the version of node to the latest one?@ak239

**Comment by ak239** [comment]
I tried to install `brew` on my mac and it looks like it works just fine with both node@8 and node@10.
Could you try to cd into `/usr/local/lib/node_modules/ndb` folder and run `npm install` from there?
You can try to run `brew doctor` as well.

**Comment by wenjiasen** [comment]
I reinstall node, it works! Thanks for your help!

**Comment by ak239** [comment]
You are welcome. 😎
